apiVersion: v1
data:
  application.properties: |-
    spring.main.banner-mode=off
    spring.jpa.hibernate.ddl-auto=update
    spring.datasource.url=jdbc:mysql://mariadb:3306/db_todo
    spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
    spring.datasource.username=springuser
    spring.datasource.password=mypassword-quoor-uHoe7z
kind: ConfigMap
metadata:
  name: spring-app