---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
  labels:
    db: mariadb
  name: mariadb
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      db: mariadb
  template:
    metadata:
      annotations:
      labels:
        db: mariadb
    spec:
      containers:
      - env:
        - name: MYSQL_USER
          value: springuser
        - name: MYSQL_PASSWORD
          value: mypassword-quoor-uHoe7z
        - name: MYSQL_DATABASE
          value: db_todo
        - name: MYSQL_ROOT_PASSWORD
          value: r00t-aeKie8ahWai_
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: 'mariadb:10.3.10'
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 3306
            protocole: TCP
            name: mysqlport
        securityContext:
          privileged: false
