---
apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    db: mariadb
  name: mariadb
spec:
  clusterIP: None
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    db: mariadb
