---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    fabric8.io/iconUrl: img/icons/spring-boot.svg
  labels:
    app: prez-fabric8-dmp
  name: prez-fabric8-dmp
spec:
  replicas: 2
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: prez-fabric8-dmp
      provider: fabric8
      group: io.github.kanedafromparis
  template:
    metadata:
      annotations:
      labels:
        app: prez-fabric8-dmp
    spec:
      volumes:
      - name: config-volume
        configMap:
          name: spring-app
      containers:
      - env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: kanedafromparis/${project.artifactId}:${project.version}
        imagePullPolicy: IfNotPresent
        name: kanedafromparis-prez-fabric8-dmp
        volumeMounts:
        - name: config-volume
          mountPath: /opt/${project.artifactId}/conf
        securityContext:
          privileged: false
