---
apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    app: prez-fabric8-dmp
  name: prez-fabric8-dmp
spec:
  clusterIP: None
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: prez-fabric8-dmp
